### PR TITLE
Pull request for facebook share and like

### PR DESCRIPTION
**Pull request by myselfsourav**

### CODE REVIEW

**Comment by myselfsourav** [comment]
facebook
(Location : /themes/point/images)
fancybox_overlay
fancybox_sprite

(The above two location is : \themes\point\css\images)

**Comment by myselfsourav** [comment]
fancybox_overlay
fancybox_sprite
(The above two location is : \themes\point\css\images)
facebook
(Location : /themes/point/images)

**Comment by myselfsourav** [comment]
The latest pull request with the images

**Comment by leerob727** [comment]
have merged changes separately

**Pull request closed without merging**
